-- =============================================================
-- HIPANAO SOLUTIONS - Migration: Additional Student Information
-- fields (Secondary/Boarding, Education, Requirements)
--
-- PAANO GAMITIN:
-- 1. Buksan ang phpMyAdmin, piliin ang iyong "alumni_db" database.
-- 2. Pumunta sa tab na "SQL".
-- 3. I-paste ang BUONG laman ng file na ito, tapos i-click ang "Go".
-- 4. Ligtas itong i-run kahit may laman na ang tblstudent mo -
--    ADD COLUMN lang ito, walang dinedelete o binabago sa
--    kasalukuyan mong datos.
--
-- Kung sakaling paulit-ulit mong i-run ito (halimbawa, hindi mo
-- na-verify kung natapos na noong una), gagamitin ang
-- IF NOT EXISTS-style na pattern sa ibaba (via stored procedure)
-- para hindi mag-error kahit meron nang column - ligtas i-re-run.
-- =============================================================

DELIMITER $$

DROP PROCEDURE IF EXISTS hipanao_add_student_fields$$
CREATE PROCEDURE hipanao_add_student_fields()
BEGIN

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'OTHER_PERSON_SUPPORTING') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `OTHER_PERSON_SUPPORTING` varchar(150) DEFAULT NULL AFTER `GUARDIAN_ADDRESS`;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'IS_BOARDING') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `IS_BOARDING` varchar(5) DEFAULT 'No' AFTER `OTHER_PERSON_SUPPORTING`;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'WITH_FAMILY') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `WITH_FAMILY` varchar(5) DEFAULT 'Yes' AFTER `IS_BOARDING`;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'BOARDING_ADDRESS') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `BOARDING_ADDRESS` text DEFAULT NULL AFTER `WITH_FAMILY`;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'ELEM_SCHOOL') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `ELEM_SCHOOL` varchar(150) DEFAULT NULL AFTER `BOARDING_ADDRESS`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'ELEM_ADDRESS') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `ELEM_ADDRESS` varchar(255) DEFAULT NULL AFTER `ELEM_SCHOOL`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'ELEM_YEAR') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `ELEM_YEAR` varchar(20) DEFAULT NULL AFTER `ELEM_ADDRESS`;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'SEC_SCHOOL') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `SEC_SCHOOL` varchar(150) DEFAULT NULL AFTER `ELEM_YEAR`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'SEC_ADDRESS') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `SEC_ADDRESS` varchar(255) DEFAULT NULL AFTER `SEC_SCHOOL`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'SEC_YEAR') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `SEC_YEAR` varchar(20) DEFAULT NULL AFTER `SEC_ADDRESS`;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'COLLEGE_SCHOOL') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `COLLEGE_SCHOOL` varchar(150) DEFAULT NULL AFTER `SEC_YEAR`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'COLLEGE_ADDRESS') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `COLLEGE_ADDRESS` varchar(255) DEFAULT NULL AFTER `COLLEGE_SCHOOL`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'COLLEGE_YEAR') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `COLLEGE_YEAR` varchar(20) DEFAULT NULL AFTER `COLLEGE_ADDRESS`;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'VOC_SCHOOL') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `VOC_SCHOOL` varchar(150) DEFAULT NULL AFTER `COLLEGE_YEAR`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'VOC_ADDRESS') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `VOC_ADDRESS` varchar(255) DEFAULT NULL AFTER `VOC_SCHOOL`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'VOC_YEAR') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `VOC_YEAR` varchar(20) DEFAULT NULL AFTER `VOC_ADDRESS`;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'OTHERS_SCHOOL') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `OTHERS_SCHOOL` varchar(150) DEFAULT NULL AFTER `VOC_YEAR`;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_FORM138') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_FORM138` tinyint(1) NOT NULL DEFAULT 0 AFTER `OTHERS_SCHOOL`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_GOODMORAL') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_GOODMORAL` tinyint(1) NOT NULL DEFAULT 0 AFTER `REQ_FORM138`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_BIRTHCERT') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_BIRTHCERT` tinyint(1) NOT NULL DEFAULT 0 AFTER `REQ_GOODMORAL`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_BAPTISMAL') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_BAPTISMAL` tinyint(1) NOT NULL DEFAULT 0 AFTER `REQ_BIRTHCERT`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_ASSESSMENT') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_ASSESSMENT` tinyint(1) NOT NULL DEFAULT 0 AFTER `REQ_BAPTISMAL`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_TRANSFERCRED') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_TRANSFERCRED` tinyint(1) NOT NULL DEFAULT 0 AFTER `REQ_ASSESSMENT`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_MARRIAGECONTRACT') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_MARRIAGECONTRACT` tinyint(1) NOT NULL DEFAULT 0 AFTER `REQ_TRANSFERCRED`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_2X2PICTURE') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_2X2PICTURE` tinyint(1) NOT NULL DEFAULT 0 AFTER `REQ_MARRIAGECONTRACT`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_OTHERS1') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_OTHERS1` varchar(150) DEFAULT NULL AFTER `REQ_2X2PICTURE`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_OTHERS2') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_OTHERS2` varchar(150) DEFAULT NULL AFTER `REQ_OTHERS1`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_OTHERS3') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_OTHERS3` varchar(150) DEFAULT NULL AFTER `REQ_OTHERS2`;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tblstudent' AND COLUMN_NAME = 'REQ_NOTES') THEN
        ALTER TABLE `tblstudent` ADD COLUMN `REQ_NOTES` text DEFAULT NULL AFTER `REQ_OTHERS3`;
    END IF;

END$$

DELIMITER ;

CALL hipanao_add_student_fields();
DROP PROCEDURE IF EXISTS hipanao_add_student_fields;
